name: Lint and Unit Test
on:
  push:
    branches:
      main

jobs:
  lint_and_unittest:
    name: "Lint Check and Unit test"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run Lint
        run: ./gradlew lintDebug

      - name: Upload Lint Report (HTML)
        uses: actions/upload-artifact@v4
        with:
          name: lint-reports
          path: '**/build/reports/lint-results-*.html'

      - name: Run Unit Test
        run: ./gradlew testDebugUnitTest

      - name: Upload Unit Test Report (HTML)
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: '**/build/reports/tests/testDebugUnitTest/index.html'